### ISSUE TITLE
Screen goes black when MMM-Sounds is in config.js

### ISSUE THREAD

**Issue by LucMacPaquet** [jc21/MMM-Sounds#1]
Hi

My raspberry is able to play sound through the sound jack. I installed MMM-Sounds like all others modules by following instructions. When I put the config lines for MMM-Sounds inside config.js, when I restart Magic Mirror, the screen goes black. No module are showing up. I go back to config.js, comment lines about MMM-Sounds and restart Magic Mirror, the Magic Mirror and modules are fine. 
Are you aware of conflict with other module?
Thanks

**Comment by jc21** [comment]
I am not aware but I haven't used this plugin lately either. It would seem that there is a JS error either in the frontend or on the server side. You'll be able to see the frontend errors if you load your mirror site up in a browser and enable developer tools to see any errors in the console.

**Comment by LucMacPaquet** [comment]
I remove all modules in config.js and still got a black screen. The server seems to be down because I cannot access it from a my Mac's Chrome. The mirror log said that : 
0|mm       | > magicmirror@2.1.1 start /home/pi/MagicMirror
0|mm       | > sh run-start.sh
0|mm       | Starting MagicMirror: v2.1.1
0|mm       | Loading config ...
0|mm       | Loading module helpers ...
0|mm       | Initializing new module helper ...
0|mm       | WARNING! Could not load config file. Starting with default configuration. Error found: TypeError: m.loaded is not a function
0|mm       | Loading module helpers ...
0|mm       | Initializing new module helper ...
0|mm       | App threw an error during load
0|mm       | TypeError: m.loaded is not a function
0|mm       |     at loadModule (/home/pi/MagicMirror/js/app.js:144:6)
0|mm       |     at loadNextModule (/home/pi/MagicMirror/js/app.js:161:5)
0|mm       |     at loadModules (/home/pi/MagicMirror/js/app.js:172:3)
0|mm       |     at /home/pi/MagicMirror/js/app.js:218:4
0|mm       |     at loadConfig (/home/pi/MagicMirror/js/app.js:77:4)
0|mm       |     at App.start (/home/pi/MagicMirror/js/app.js:206:3)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/js/electron.js:102:6)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/js/electron.js:106:3)
0|mm       |     at Module._compile (module.js:571:32)
0|mm       |     at Object.Module._extensions..js (module.js:580:10)
0|mm       | Whoops! There was an uncaught exception...
0|mm       | TypeError: m.loaded is not a function
0|mm       |     at loadModule (/home/pi/MagicMirror/js/app.js:144:6)
0|mm       |     at loadNextModule (/home/pi/MagicMirror/js/app.js:161:5)
0|mm       |     at loadModules (/home/pi/MagicMirror/js/app.js:172:3)
0|mm       |     at /home/pi/MagicMirror/js/app.js:218:4
0|mm       |     at loadConfig (/home/pi/MagicMirror/js/app.js:77:4)
0|mm       |     at App.start (/home/pi/MagicMirror/js/app.js:206:3)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/js/electron.js:102:6)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/js/electron.js:106:3)
0|mm       |     at Module._compile (module.js:571:32)
0|mm       |     at Object.Module._extensions..js (module.js:580:10)
0|mm       | MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm       | If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
0|mm       | Launching application.

**Comment by LucMacPaquet** [comment]
And this is when everything is fine. You can see that module helper seems to be the problem if you compare with the previous error log. 

Starting MagicMirror: v2.1.1
0|mm       | Loading config ...
0|mm       | Loading module helpers ...
0|mm       | No helper found for module: alert.
0|mm       | Initializing new module helper ...
0|mm       | Module helper loaded: updatenotification
0|mm       | Initializing new module helper ...
0|mm       | Module helper loaded: MMM-IFTTT
0|mm       | No helper found for module: MMM-Globe.
0|mm       | Initializing new module helper ...
0|mm       | Module helper loaded: MMM-Trello
0|mm       | No helper found for module: clock.
0|mm       | No helper found for module: currentweather.
0|mm       | No helper found for module: weatherforecast.
0|mm       | Initializing new module helper ...
0|mm       | Module helper loaded: newsfeed
0|mm       | Initializing new module helper ...
0|mm       | Module helper loaded: calendar
0|mm       | All module helpers loaded.
0|mm       | Starting server on port 8080 ... 
0|mm       | Starting server op port 8080 ... 
0|mm       | You're using a full whitelist configuration to allow for all IPs
0|mm       | Server started ...
0|mm       | Connecting socket for: updatenotification
0|mm       | Connecting socket for: MMM-IFTTT
0|mm       | [2017-05-17 19:12:02] [MMM-IFTTT] Starting node_helper
0|mm       | Connecting socket for: MMM-Trello
0|mm       | Starting node helper for: MMM-Trello
0|mm       | Connecting socket for: newsfeed
0|mm       | Starting module: newsfeed
0|mm       | Connecting socket for: calendar
0|mm       | Starting node helper for: calendar
0|mm       | Sockets connected & modules started ...
0|mm       | Launching application.

**Comment by jc21** [comment]
Finally got to this. Pull the module again, should be fixed now.

**Comment by LucMacPaquet** [comment]
Big thanks. Everything is fine now.
